// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type Usize = number;
    export type MapInfo = {

        /**
         * The highest zoom level. The total amount of zoom levels is this +1.
         */
        "max_zoom_level": types.Usize;
        "tile_size": types.Usize;
    };
    export type MapInfoList = {

        /**
         * A hashmap of map index to map info.
         */
        "maps": Record<types.Usize, types.MapInfo>;
    };
}
