// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types{
export type I32=number;
export type U32=number;
export type F32=number;
export type ItemData={"name":(string|null);"temp_name":(string|null);"temp_end_event":(string|null);"sort":types.I32;"img_no":types.I32;"price":types.U32;"lv":types.U32;"element":(types.U32|null);"element_value":(types.U32|null);"elem_fire":(types.I32|null);"elem_ice":(types.I32|null);"elem_thunder":(types.I32|null);"elem_air":(types.I32|null);"pc":(types.I32)[];"hp":(types.I32|null);"atk":(types.I32|null);"def":(types.I32|null);"spd":(types.I32|null);"w_hp":(types.F32|null);"w_mp":(types.F32|null);"w_atk":(types.F32|null);"w_def":(types.F32|null);"w_spd":(types.F32|null);"dlc":(string)[];"use_tag":string;"kind_tag":string;"bme":(string|null);"bmee":(string|null);"cat":(string)[];};
export type Ryza3Data={"item_data":(types.ItemData)[];};
}
